"""S82: offline generator, f64 angular quadrature; runtime reads fixed f32 bits."""
import math, struct
from pathlib import Path
cosines=[math.cos(math.tau*(i+0.5)/2048) for i in range(2048)]
def bits(v): return struct.unpack('<I',struct.pack('<f',v))[0]
rows=[]
for i in range(1025):
    x=i/16
    a=math.fsum(math.cos(x*c) for c in cosines)/2048
    b=math.fsum(c*math.sin(x*c) for c in cosines)/2048
    derivative=0.5 if i==0 else a-b/x
    rows.append('['+', '.join(f'f32::from_bits(0x{bits(v):08x})' for v in (a,b,derivative))+'],')
Path(__file__).resolve().parents[1].joinpath('src/bessel_table.rs').write_text('// Generated by examples/generate_bessel.py; J0, J1, J1 derivative.\npub(crate) const TABLE: [[f32;3];1025] = [\n'+'\n'.join(rows)+'\n];\n',encoding='utf-8')
